server:
  port: ${PORT:4001}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URL}/cloud
  application:
    name: CLOUD-BACKEND-SERVICE
  mail:
    host: ${EMAIL_HOST}
    port: 587
    username: ${EMAIL}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


app:
  mqtt:
    broker: ${MQTT_BROKER}
    username: ${MQTT_USERNAME}
    clientId: ${spring.application.name}
    password: ${MQTT_PASSWORD}
  utils:
    auth-service-base-url: http://localhost:${server.port}
    open-api-endpoints:
      - "/auth/sign-up"
      - "/auth/login"
      - "/auth/validate"
      - "/auth/generate-otp"
      - "/auth/verify-otp"
    open-api-end-points-for-account:
      - "/accounts"
      - "/roles"
      - "/accounts/validate"
      - "/auth/update-token"

  communication:
    from: ${spring.mail.username}
  auth:
    account-gateway:
      base-url: http://localhost:${server.port}
      validate-role-and-account-path: '/accounts/validate'

  widgets:
    node-bff:
      base-url: ${NODE_BFF_URL}/api
